### PR TITLE
PHP 8.1 support

### PR DESCRIPTION
**Pull request by boesing**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

Initial PHP 8.1 support.

### CODE REVIEW

**Comment by geerteltink** [comment]
Interesting to see this. Why did we choose `~8.0.0` for PHP restrictions? Why not `^8.0`?

**Comment by samsonasik** [comment]
@geerteltink we discussed about it, PHP is not using semver.

**Comment by geerteltink** [comment]
I didn't know that. So basically they can break stuff in minor releases?

**Comment by samsonasik** [comment]
yes

**Review by Ocramius — APPROVED** [review]

**Pull request merged**
