### PR TITLE
show version 3.5 of the installer

### PR DESCRIPTION
**Pull request by dominikzogg**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Update screenshot with an actual ones

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by dominikzogg** [comment]
@samsonasik do you have an idea if those user images stays for ever or it i have to mark them somehow to stay? Not that the readme breaks over time

**Comment by samsonasik** [comment]
I think change image installer only when there is new feature, eg: added "chubbyphp-container" container like in current container options. So, not in every new release.

**Comment by dominikzogg** [comment]
@samsonasik sorry, i meant, if you or someone else is aware of, if github deletes images uploaded to https://user-images.githubusercontent.com over time?

**Comment by samsonasik** [comment]
I have 2015 image uploaded to github, and it still exists

**Pull request merged**
