### PR TITLE
move "laminas/laminas-development-mode" to require to allow run it after run --no-dev

### PR DESCRIPTION
**Pull request by samsonasik**
eg: on production environment we can run:

```bash
RUN /usr/bin/composer install --prefer-dist --no-dev
RUN export APPLICATION_ENV=production && /usr/bin/composer development-disable
```

Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### CODE REVIEW

**Comment by samsonasik** [comment]
it disable it: `composer development-disable`

**Comment by michalbundyra** [comment]
To disable, you need to have it enabled first - and - default behaviour is "disabled by default". 
Cannot see reason to have it available on prod, tbh.

**Comment by samsonasik** [comment]
sometime, there is a condition of "debug in production", while that's not the right way, that can happen, so running `composer development-enable` for debugging can be an option.

**Comment by froschdesign** [comment]
@samsonasik 
> sometime, there is a condition of "debug in production"…

In the readme file we have:

> **Note:** Do NOT run development mode on your production server!

https://github.com/mezzio/mezzio-skeleton#to-enable-development-mode

**Comment by michalbundyra** [comment]
@samsonasik 

> sometime, there is a condition of "debug in production"...

as I said before, we _should not_ propagate "wrong behaviours". There are many different options than hacking live, production application. Of course for serious applications...

**Comment by samsonasik** [comment]
ok, understood ;). I'm closing it.

**Pull request closed without merging**
