### PR TITLE
Update dependency elie29/zend-phpdi-config to accept v9

### PR DESCRIPTION
**Pull request by elie29**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | yes
| RFC           | yes
| QA            | no

### Description

Update  [elie29/zend-phpdi-config](https://github.com/elie29/zend-di-config) to accept v9.0 in order to be compatible with php 8.1

<br class="Apple-interchange-newline">
</body>
</html>

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
This patch is alright, but I suggest doing it with `composer update nothing` to force just the `content-hash` to update.

That should keep the lock file compatible with the current setup, whilst allowing installation on newer versions too.

**Comment by Ocramius** [comment]
Actually, your patch is good, just unsure about these reported issues:

```
 Error: src/MezzioInstaller/OptionalPackages.php:245:13: MixedAssignment: Unable to determine the type that $answer is being assigned to (see https://psalm.dev/032)
Error: src/MezzioInstaller/OptionalPackages.php:621:13: MixedAssignment: Unable to determine the type that $answer is being assigned to (see https://psalm.dev/032)
Error: src/MezzioInstaller/OptionalPackages.php:634:89: MixedArgument: Argument 2 of preg_match cannot be mixed, expecting string (see https://psalm.dev/030)
```

I wonder if we should just baseline those: they are only related to the console abstractions.

**Comment by elie29** [comment]
@Ocramius I created #84 PR, if you want to merge immediately the main branch 3.12.x so you can compare hashes directly.

Thanks

**Review by Ocramius — APPROVED** [review]
Thanks @elie29!

**Pull request merged**
