### PR TITLE
fix pimple and auryn containerName cases

### PR DESCRIPTION
**Pull request by pine3ree**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

The container used by the home-page handler factory could be a pimple psr11-wrapper `Pimple\Psr11\Container`, not a `Pimple\Container` instance.

### CODE REVIEW

**Comment by pine3ree** [comment]
see: https://github.com/mezzio/mezzio-skeleton/issues/4, I totally forgot I also opened an issue for it as well.

**Comment by michalbundyra** [comment]
@pine3ree what about importing also test case from https://github.com/zendframework/zend-expressive-skeleton/pull/270/files? :)

it looks like we do have also wrong link to Aura.Di container - we link to v2, but laminas-auradi-config supports v3.4+. Also by chance noticed that the latest version for Aura.Di is v4 and we do not have support for it yet - created issue, see: https://github.com/laminas/laminas-auradi-config/issues/2

**Comment by pine3ree** [comment]
Hello @michalbundyra, 
right I totally forgot I added a test case as well at that time. I updated it and included it in this pacth (sorry for the `patch-1` name...I made it online since I tough it was just a string correction). I also fixed the auryn container case with the psr wrapper fqcn.

I found another PR (https://github.com/zendframework/zend-expressive-skeleton/pull/271) I am going to re-submitt to thi repo.

Quick Q: why DCO fails with `Signed-off-by:name` (no space after ":"), at first I thought the failure was to to a blank line missing between the commit-message and the signed-off string... :-)

**Comment by weierophinney** [comment]
@pine3ree —

> Quick Q: why DCO fails with `Signed-off-by:name` (no space after ":"), at first I thought the failure was to to a blank line missing between the commit-message and the signed-off string... :-)

File an issue about that at the [DCO bot repo](https://github.com/probot/dco), please. :smile:

**Comment by pine3ree** [comment]
@weierophinney 
> > Quick Q: why DCO fails with `Signed-off-by:name` (no space after ":"), at first I thought the failure was to to a blank line missing between the commit-message and the signed-off string... :-)
> 
> File an issue about that at the [DCO bot repo](https://github.com/probot/dco), please.

I am trying to find the source of the bug in netbeans-src: I have found the config-property but not the place where the commit message is decorated with the wrong signOff line... :smile::

**Comment by michalbundyra** [comment]
Thanks, @pine3ree!

**Pull request merged**
